---

- name: aci vrf deletion
  hosts: apic1
  gather_facts: False

  tasks:
    - name: delete a vrf
      aci_vrf:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        vrf: vrf-1
        description: vrf 1
        tenant: Ansible
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: absent

