---

- name: aci vrf query
  hosts: apic1
  gather_facts: False

  tasks:
    - name: query to validate if vrf is present
      aci_vrf:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        vrf: "{{ item.name }}"
        tenant: "{{ item.tenant }}"
        state: query
      with_items: "{{ vrfs }}"
      register: output

    - debug:
        msg: "{{ output }}"

