---

- name: aci epg creation with list
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Add a new epg
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        description: "{{ item.description }}"
        bd: "{{ item.bd }}"
        state: present
      with_items: "{{ epg }}"

    - name: Add a new domain to EPG binding
      aci_epg_to_domain:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        domain: "{{ item.domain }}"
        domain_type: "{{ item.domain_type }}"
        vm_provider: "{{ item.vm_provider }}"
        state: present
      with_items: "{{ epg }}"

    - name: Add a new contract for EPG to EPG Communication
      aci_epg_to_contract:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        contract: "{{ item.name }}"
        contract_type: "{{ item.type }}"
        state: present
      with_items: "{{ epg_contracts }}"


    - name: Add a new contract for EPG to L3OUT Communication
      aci_epg_to_contract:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        contract: "{{ item.name }}"
        contract_type: "{{ item.type }}"
        state: present
      with_items: "{{ l3out_contracts }}"
