---

- name: aci epg query with list
  hosts: apic1
  gather_facts: False

  tasks:
    - name: query epg
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        state: query
      with_items: "{{ epg }}"
      register: output

    - debug:
        msg: "{{ output }}"
