---

- name: aci epg query all
  hosts: apic1
  gather_facts: False

  tasks:
    - name: query all epgs
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        state: query
      register: output

    - debug:
        msg: "{{ output }}"
