---

- name: aci anp creation
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Add a new enp
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: Ansible
        ap: ANP-APP-1
        description: Application Profile
        state: present
