---

- name: aci tenant creation
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Add a new ANP to Tenant
      aci_ap:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      with_items: "{{ anps }}"
