---

- name: aci application profile query
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Query application profile
      aci_ap:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: Ansible
        ap: ANP-APP-1
        state: query
      register: output

    - debug:
        msg: "{{ output.current[0] }}"
