---

- name: aci bd deletion with items
  hosts: apic1
  gather_facts: False

  tasks:
    - name: delete bd
      aci_bd:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        bd: "{{ item.name }}"
        state: absent
      with_items: "{{ bds }}"
