---

tenants:
  - name: "Ansible_Tenant_1"
    description: "Created by Ansible"
  - name: "Ansible_Tenant_2"
    description: "Created by Ansible"
  - name: "Ansible_Tenant_3"
    description: "Created by Ansible"


