---

- name: VM Deletion
  hosts: vsphere
  gather_facts: False

  tasks:
    - name: Delete VM
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        name: "{{ name }}"
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - debug:
        msg: "{{ deploy }}"
