---

- name: aci epg creation with list
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Add a new epg
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        description: "{{ item.description }}"
        bd: "{{ item.bd }}"
        state: present
      with_items: "{{ epg }}"
