---

- name: aci epg deletion
  hosts: apic1
  gather_facts: False

  tasks:
    - name: delete epg
      aci_epg:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        tenant: Ansible
        ap: "ANP-APP-1"
        epg: "EPG-1"
        state: absent
