---

- name: aci anp query all
  hosts: apic1
  gather_facts: False

  tasks:
    - name: Query anp
      aci_ap:
        host: apic1
        username: "{{ username }}"
        password: "{{ password }}" 
        validate_certs: no
        state: query
      register: output

    - debug:
        msg: "{{ output.current[1] }}"
